# Generated by Django 5.1.7 on 2025-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swiggy_main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(default="534001", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="street_address",
            field=models.TextField(default="11-32, Balayya Cheruvu Street"),
            preserve_default=False,
        ),
    ]
